name: file-server

services:
  db:
    image: postgres:17
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./BackEnd
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./BackEnd:/app
      - ./storage:/storage
    ports:
      - "8000:8000"
    environment:
      - STORAGE_DIR=/storage
      - MAX_UPLOAD_MB=${MAX_UPLOAD_MB:-100}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173}
      - ALLOWED_MIME_TYPES=${ALLOWED_MIME_TYPES:-}
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

volumes:
  db-data:
